### ISSUE TITLE
social icons

### ISSUE THREAD

**Issue by codexmon** [codexmon/k5games#8]
social icons to connect with github and linkedin for header and footer navigation

**Comment by Aaron-Junker** [comment]
I would like to work on this

**Comment by codexmon** [comment]
awesome! i'll assign you to this issue :)

**Comment by Aaron-Junker** [comment]
What's the name of your linkedin?

**Comment by codexmon** [comment]
it's fine to use the placeholder: https://www.linkedin.com - i'll link it when i clean it up a bit. thanks in advance!
